services:
  # Mariadb
  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: iaw
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

  # Apache
  apache:
    build: .
    container_name: apache_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

volumes:
  db_data: